- name: Import GoLang from Common Role
  ansible.builtin.include_role:
    name: common
    tasks_from: golang

- name: Load mysql-schema
  ansible.builtin.include_role:
    name: common
    tasks_from: mysql-schema

- name: Load Master Data
  ansible.builtin.shell: mysql -h mysql-{{ env }}.rdevopsb89.online -u root -pRoboShop@1 {{ component_name }} < db/master-data.sql
  args:
    chdir: /app

