- name: Download prometheus exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.11.1/node_exporter-1.11.1.linux-amd64.tar.gz
    dest: /opt

- name: Create prometheus service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=node_exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      Type=simple
      ExecStart=/opt/node_exporter-1.11.1.linux-amd64/node_exporter --collector.systemd

      [Install]
      WantedBy=multi-user.target

- name: Start node_exporter
  ansible.builtin.systemd_service:
    name: node_exporter
    state: restarted
    enabled: yes



